// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUYWs-qru2MnCkpejQAwqHRkaUcdacw8',
    appId: '1:681222842940:web:757f57a87ae7537f7b7139',
    messagingSenderId: '681222842940',
    projectId: 'fashion-app-hammad0420',
    authDomain: 'fashion-app-hammad0420.firebaseapp.com',
    storageBucket: 'fashion-app-hammad0420.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNY4uWTLCJontFiNzJh1XvFa3cap-RFY',
    appId: '1:681222842940:android:570c29b81d878d8f7b7139',
    messagingSenderId: '681222842940',
    projectId: 'fashion-app-hammad0420',
    storageBucket: 'fashion-app-hammad0420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTQb3dw8N8-FE_G590W3Iqmaqb8SxWMI',
    appId: '1:681222842940:ios:5a930d98734939bd7b7139',
    messagingSenderId: '681222842940',
    projectId: 'fashion-app-hammad0420',
    storageBucket: 'fashion-app-hammad0420.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTQb3dw8N8-FE_G590W3Iqmaqb8SxWMI',
    appId: '1:681222842940:ios:5a930d98734939bd7b7139',
    messagingSenderId: '681222842940',
    projectId: 'fashion-app-hammad0420',
    storageBucket: 'fashion-app-hammad0420.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfUYWs-qru2MnCkpejQAwqHRkaUcdacw8',
    appId: '1:681222842940:web:1a4f8687f96b7aa67b7139',
    messagingSenderId: '681222842940',
    projectId: 'fashion-app-hammad0420',
    authDomain: 'fashion-app-hammad0420.firebaseapp.com',
    storageBucket: 'fashion-app-hammad0420.firebasestorage.app',
  );
}
